### ISSUE TITLE
Remove repository

### ISSUE THREAD

**Issue by thijslemmens** [AlfrescoLabs/alfresco-gradle-plugins#5]
This repository is outdated, and no longer usable. However it still pops up on google, and I people loose time trying this out.
Please remove this repo, or clearly indicate that it is dead. There is a maintained gradle SDK for Alfresco here:
https://github.com/xenit-eu/alfresco-gradle-sdk

**Comment by jottley** [comment]
Thanks for the feedback.  I think this is a great idea.  I'll archive the project and update the README to point at Xenit's project.
